title: Amanda Busha # your name (or website title) here
logo: "/images/pic1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br><br>
 Former educator reinventing myself as a tech savvy analytics professional.  
  <br><br>
  <a href="https://www.linkedin.com/in/amanda-busha-02a69a1a4/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
